----EMPLOYEE MANAGEMNET--------

--Create Department Table
/*
CREATE TABLE departments (
    dept_id NUMBER PRIMARY KEY,
    dept_name VARCHAR2(100)
);
*/


--Create employees Table
/*
CREATE TABLE employees (
    emp_id NUMBER PRIMARY KEY,
    emp_name VARCHAR2(100),
    salary NUMBER(10,2),
    dept_id NUMBER,
    hire_date DATE,
    status VARCHAR2(20),
    CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES departments(dept_id)
);
*/


---Create Audit Table
/*
 CREATE TABLE employee_audit (
     audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
     emp_id NUMBER,
     action_type VARCHAR2(50),
     action_date DATE
 );
*/

/*
INSERT INTO departments VALUES (1, 'HR');
INSERT INTO departments VALUES (2, 'IT');
INSERT INTO departments VALUES (3, 'Finance');
COMMIT;
*/

-------------------ADD EMPLOYEE ----------------------
CREATE OR REPLACE PROCEDURE add_employee (
    p_emp_id NUMBER,p_emp_name VARCHAR2,p_salary NUMBER,p_dept_id NUMBER
)
IS
BEGIN
    INSERT INTO employees (emp_id,emp_name,salary,dept_id,hire_date,status)
    VALUES ( p_emp_id,p_emp_name,p_salary,p_dept_id,SYSDATE,'ACTIVE');
    
	DBMS_OUTPUT.PUT_LINE('Employee Added Successfully');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Employee ID Already Exists');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;


----------------- CALCULATE ANNUAL SALARY----------
CREATE OR REPLACE FUNCTION annual_salary (
    p_salary NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN p_salary * 12;
END;


---------------------TRIGGER FOR AUDIT LOGGING----
CREATE OR REPLACE TRIGGER trg_employee_audit
AFTER INSERT OR UPDATE OR DELETE
ON employees
FOR EACH ROW
BEGIN

    IF INSERTING THEN

        INSERT INTO employee_audit (
            emp_id,
            action_type,
            action_date
        )
        VALUES (
            :NEW.emp_id,
            'INSERT',
            SYSDATE
        );

    ELSIF UPDATING THEN

        INSERT INTO employee_audit (
            emp_id,
            action_type,
            action_date
        )
        VALUES (
            :NEW.emp_id,
            'UPDATE',
            SYSDATE
        );

    ELSIF DELETING THEN

        INSERT INTO employee_audit (
            emp_id,
            action_type,
            action_date
        )
        VALUES (
            :OLD.emp_id,
            'DELETE',
            SYSDATE
        );

    END IF;

END;


---------Package Specification----------
CREATE OR REPLACE PACKAGE emp_package
IS

    PROCEDURE show_employee (
        p_emp_id NUMBER
    );

    PROCEDURE increase_salary (
        p_dept_id NUMBER,
        p_percent NUMBER
    );
END emp_package;
 
---------------Package Body----------
CREATE OR REPLACE PACKAGE BODY emp_package
IS

    -------------------------------------------------
    -- Show Employee Details Using Cursor
    -------------------------------------------------

    PROCEDURE show_employee (
        p_emp_id NUMBER
    )
    IS
        CURSOR c_emp IS
        SELECT emp_name, salary
        FROM employees
        WHERE emp_id = p_emp_id;

        v_name employees.emp_name%TYPE;
        v_salary employees.salary%TYPE;

    BEGIN

        OPEN c_emp;

        FETCH c_emp INTO v_name, v_salary;

        IF c_emp%FOUND THEN

            DBMS_OUTPUT.PUT_LINE('Employee Name : ' || v_name);
            DBMS_OUTPUT.PUT_LINE('Salary        : ' || v_salary);

        ELSE

            DBMS_OUTPUT.PUT_LINE('Employee Not Found');

        END IF;

        CLOSE c_emp;

    END show_employee;

    -------------------------------------------------
    -- Bulk Salary Update
    -------------------------------------------------

    PROCEDURE increase_salary (
        p_dept_id NUMBER,
        p_percent NUMBER
    )
    IS

        TYPE emp_array IS TABLE OF employees.emp_id%TYPE;

        v_emp_ids emp_array;

    BEGIN

        SELECT emp_id BULK COLLECT INTO v_emp_ids FROM employees WHERE dept_id = p_dept_id;

        FORALL i IN 1 .. v_emp_ids.COUNT

            UPDATE employees
            SET salary = salary + (salary * p_percent / 100)
            WHERE emp_id = v_emp_ids(i);

        DBMS_OUTPUT.PUT_LINE('Salary Updated Successfully');

    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(SQLERRM);

    END increase_salary;
END emp_package;

----------Create Index for Performance---------------
CREATE INDEX idx_emp_dept ON employees(dept_id);


-------------- TESTING--------------
--Add a employee 
BEGIN
    add_employee(101,'Arjun Kumar',50000,2 );
END;
---view annual salary
SELECT annual_salary(50000) FROM dual;
-------- see employee of id:101
SET SERVEROUTPUT ON
BEGIN
    emp_package.show_employee(101);
END;
---Bulk salary increment
-- department 2 salary increase 10% of all employees
BEGIN
emp_package.increase_salary(2,10);
END;

---------view two main table
SELECT * FROM employees;
SELECT * FROM employee_audit;
